-- ========================
-- ICONDB 개선된 스키마 (v2)
-- PostgreSQL + Supabase
-- ========================

-- ========================
-- 1. User 테이블 (개선)
-- ========================
CREATE TABLE
  "public"."user" (
    "id" character varying(255) PRIMARY KEY,
    "email" character varying(255) NOT NULL UNIQUE,
    "password" character varying(255) NOT NULL,
    "nickname" character varying(100) NOT NULL UNIQUE,
    "bio" text,
    "profile_image_url" character varying(500),
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    "deleted_at" timestamp with time zone,
    constraint "user_email_unique" unique ("email"),
    constraint "user_nickname_unique" unique ("nickname")
  ) tablespace pg_default;

-- ========================
-- 2. Content 테이블 (개선)
-- ========================
CREATE TABLE
  "public"."content" (
    "id" bigint generated by default as identity PRIMARY KEY,
    "user_id" character varying(255) NOT NULL,
    "title" character varying(255) NOT NULL,
    "description" text,
    "svg_key" character varying(255) NOT NULL UNIQUE,
    "view_count" bigint DEFAULT 0,
    "like_count" bigint DEFAULT 0,
    "is_public" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    constraint "content_user_id_fkey" 
        foreign key ("user_id") references "public"."user" ("id") on delete cascade
  ) tablespace pg_default;

-- ========================
-- 3. Tag 테이블 (정규화됨)
-- ========================
-- 글로벌 태그 (모든 사용자가 공유)
CREATE TABLE
  "public"."tag" (
    "id" bigint generated by default as identity PRIMARY KEY,
    "name" character varying(100) NOT NULL UNIQUE,
    "description" text,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text)
  ) tablespace pg_default;

-- ========================
-- 4. Content-Tag 연결 (다대다)
-- ========================
CREATE TABLE
  "public"."content_tag" (
    "id" bigint generated by default as identity PRIMARY KEY,
    "content_id" bigint NOT NULL,
    "tag_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    constraint "unique_content_tag" unique ("content_id", "tag_id"),
    constraint "content_tag_content_id_fkey" 
        foreign key ("content_id") references "public"."content" ("id") on delete cascade,
    constraint "content_tag_tag_id_fkey" 
        foreign key ("tag_id") references "public"."tag" ("id") on delete cascade
  ) tablespace pg_default;

-- ========================
-- 5. Like 테이블 (개선 - 중복 방지)
-- ========================
CREATE TABLE
  "public"."like" (
    "id" bigint generated by default as identity PRIMARY KEY,
    "user_id" character varying(255) NOT NULL,
    "content_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    -- 중복 방지
    constraint "unique_user_content_like" unique ("user_id", "content_id"),
    constraint "like_user_id_fkey" 
        foreign key ("user_id") references "public"."user" ("id") on delete cascade,
    constraint "like_content_id_fkey" 
        foreign key ("content_id") references "public"."content" ("id") on delete cascade
  ) tablespace pg_default;

-- ========================
-- 6. Follow 테이블 (개선 - 자기 팔로우 방지)
-- ========================
CREATE TABLE
  "public"."follow" (
    "id" bigint generated by default as identity PRIMARY KEY,
    "follower_id" character varying(255) NOT NULL,
    "followee_id" character varying(255) NOT NULL,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    -- 중복 방지
    constraint "unique_follower_followee" unique ("follower_id", "followee_id"),
    -- 자기 팔로우 방지
    constraint "follow_not_self_check" check ("follower_id" != "followee_id"),
    constraint "follow_follower_id_fkey" 
        foreign key ("follower_id") references "public"."user" ("id") on delete cascade,
    constraint "follow_followee_id_fkey" 
        foreign key ("followee_id") references "public"."user" ("id") on delete cascade
  ) tablespace pg_default;

-- ========================
-- 7. Comment 테이블 (신규)
-- ========================
CREATE TABLE
  "public"."comment" (
    "id" bigint generated by default as identity PRIMARY KEY,
    "content_id" bigint NOT NULL,
    "user_id" character varying(255) NOT NULL,
    "text" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    constraint "comment_content_id_fkey" 
        foreign key ("content_id") references "public"."content" ("id") on delete cascade,
    constraint "comment_user_id_fkey" 
        foreign key ("user_id") references "public"."user" ("id") on delete cascade
  ) tablespace pg_default;

-- ========================
-- 8. Bookmark 테이블 (신규)
-- ========================
CREATE TABLE
  "public"."bookmark" (
    "id" bigint generated by default as identity PRIMARY KEY,
    "user_id" character varying(255) NOT NULL,
    "content_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    constraint "unique_user_content_bookmark" unique ("user_id", "content_id"),
    constraint "bookmark_user_id_fkey" 
        foreign key ("user_id") references "public"."user" ("id") on delete cascade,
    constraint "bookmark_content_id_fkey" 
        foreign key ("content_id") references "public"."content" ("id") on delete cascade
  ) tablespace pg_default;

-- ========================
-- 9. Report 테이블 (신규 - 신고)
-- ========================
CREATE TABLE
  "public"."report" (
    "id" bigint generated by default as identity PRIMARY KEY,
    "reporter_id" character varying(255) NOT NULL,
    "content_id" bigint NOT NULL,
    "reason" character varying(100) NOT NULL,
    "description" text,
    "status" character varying(20) DEFAULT 'pending',
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    "resolved_at" timestamp with time zone,
    constraint "report_reporter_id_fkey" 
        foreign key ("reporter_id") references "public"."user" ("id") on delete cascade,
    constraint "report_content_id_fkey" 
        foreign key ("content_id") references "public"."content" ("id") on delete cascade
  ) tablespace pg_default;

-- ========================
-- 인덱스 최적화 (단일 인덱스)
-- ========================
CREATE INDEX idx_user_email ON "public"."user" ("email");
CREATE INDEX idx_user_is_active ON "public"."user" ("is_active");
CREATE INDEX idx_content_user_id ON "public"."content" ("user_id");
CREATE INDEX idx_content_is_public ON "public"."content" ("is_public");
CREATE INDEX idx_content_created_at ON "public"."content" ("created_at" DESC);
CREATE INDEX idx_tag_name ON "public"."tag" ("name");
CREATE INDEX idx_comment_content_id ON "public"."comment" ("content_id");
CREATE INDEX idx_comment_user_id ON "public"."comment" ("user_id");
CREATE INDEX idx_bookmark_user_id ON "public"."bookmark" ("user_id");
CREATE INDEX idx_report_status ON "public"."report" ("status");

-- ========================
-- 복합 인덱스 (성능 최적화)
-- ========================
CREATE INDEX idx_like_user_content ON "public"."like" ("user_id", "content_id");
CREATE INDEX idx_follow_follower_followee ON "public"."follow" ("follower_id", "followee_id");
CREATE INDEX idx_content_tag_content_id ON "public"."content_tag" ("content_id", "tag_id");
CREATE INDEX idx_content_user_public_created 
    ON "public"."content" ("user_id", "is_public", "created_at" DESC);

-- ========================
-- 전문 검색 인덱스 (한글)
-- ========================
CREATE INDEX idx_content_title_search 
    ON "public"."content" USING GIN(to_tsvector('korean', "title"));
CREATE INDEX idx_content_description_search 
    ON "public"."content" USING GIN(to_tsvector('korean', "description"));

-- ========================
-- Row Level Security (데이터 보호)
-- ========================
ALTER TABLE "public"."user" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."content" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."like" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."follow" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."comment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."bookmark" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."report" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."content_tag" ENABLE ROW LEVEL SECURITY;

-- ========================
-- RLS 정책 예시 (선택사항)
-- ========================
-- 사용자는 자신의 프로필만 수정 가능
CREATE POLICY "Users can update own profile" 
ON "user" FOR UPDATE USING (id = current_user_id());

-- 공개 콘텐츠는 모두 조회 가능
CREATE POLICY "Anyone can read public content" 
ON "content" FOR SELECT USING (is_public = true);

-- ========================
-- 마이그레이션 노트
-- ========================
/*
기존 데이터 마이그레이션 스크립트:

-- 1. userid → user_id 변환
-- 2. contentid → content_id 변환
-- 3. tagid → tag_id 변환
-- 4. tagname → tag name & id로 분리
-- 5. profilename → profile_image_url로 변경

마이그레이션 순서:
1. 새 테이블 생성 (위 SQL 실행)
2. 데이터 복사 (아래 마이그레이션 쿼리 실행)
3. 제약 조건 검증
4. 기존 테이블 백업 후 제거
*/

-- ========================
-- 데이터 마이그레이션 예시
-- ========================
/*
-- 사용자 데이터 복사
INSERT INTO "public"."user" 
  ("id", "email", "password", "nickname", "profile_image_url", "created_at")
SELECT 
  "id", 
  "id" || '@example.com' AS "email",  -- 임시 이메일 (수동 수정 필요)
  "password", 
  "nickname", 
  "profilename" AS "profile_image_url", 
  "created_at"
FROM old_user;

-- 콘텐츠 데이터 복사
INSERT INTO "public"."content" 
  ("user_id", "title", "svg_key", "created_at", "updated_at")
SELECT 
  "userid" AS "user_id", 
  "title", 
  "svgkey" AS "svg_key", 
  "created_at", 
  "updated_at"
FROM old_content;

-- 좋아요 데이터 복사
INSERT INTO "public"."like" 
  ("user_id", "content_id", "created_at")
SELECT 
  "userid" AS "user_id", 
  "contentid" AS "content_id", 
  "created_at"
FROM old_like;

-- 팔로우 데이터 복사 (자기 팔로우 제거)
INSERT INTO "public"."follow" 
  ("follower_id", "followee_id", "created_at")
SELECT 
  "follower" AS "follower_id", 
  "followee" AS "followee_id", 
  "created_at"
FROM old_follow
WHERE "follower" != "followee";  -- 자기 팔로우 제외
*/
