-- Supabase 데이터베이스 스키마 (PostgreSQL)
-- Supabase SQL Editor에서 다음 코드를 실행하세요

-- 1. User 테이블
CREATE TABLE
  "public"."user" (
    "id" character varying(255) NOT NULL,
    "password" character varying(255) NOT NULL,
    "nickname" character varying(100),
    "profilename" character varying(255),
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    constraint "user_pkey" primary key ("id")
  ) tablespace pg_default;

-- 2. Content 테이블 (SVG 저장)
CREATE TABLE
  "public"."content" (
    "id" bigint generated by default as identity,
    "userid" character varying(255) NOT NULL,
    "title" character varying(255),
    "svgkey" character varying(255) NOT NULL,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    constraint "content_pkey" primary key ("id"),
    constraint "content_userid_fkey" foreign key ("userid") references "public"."user" ("id") on delete cascade
  ) tablespace pg_default;

-- 3. Tag 테이블
CREATE TABLE
  "public"."tag" (
    "id" bigint generated by default as identity,
    "userid" character varying(255) NOT NULL,
    "tagname" character varying(100) NOT NULL,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    constraint "tag_pkey" primary key ("id"),
    constraint "tag_userid_fkey" foreign key ("userid") references "public"."user" ("id") on delete cascade
  ) tablespace pg_default;

-- 4. Like 테이블
CREATE TABLE
  "public"."like" (
    "id" bigint generated by default as identity,
    "userid" character varying(255) NOT NULL,
    "contentid" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    constraint "like_pkey" primary key ("id"),
    constraint "like_userid_fkey" foreign key ("userid") references "public"."user" ("id") on delete cascade,
    constraint "like_contentid_fkey" foreign key ("contentid") references "public"."content" ("id") on delete cascade
  ) tablespace pg_default;

-- 5. Follow 테이블
CREATE TABLE
  "public"."follow" (
    "id" bigint generated by default as identity,
    "follower" character varying(255) NOT NULL,
    "followee" character varying(255) NOT NULL,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    constraint "follow_pkey" primary key ("id"),
    constraint "follow_follower_fkey" foreign key ("follower") references "public"."user" ("id") on delete cascade,
    constraint "follow_followee_fkey" foreign key ("followee") references "public"."user" ("id") on delete cascade
  ) tablespace pg_default;

-- 6. Content_tag 테이블 (다대다 관계)
CREATE TABLE
  "public"."content_tag" (
    "id" bigint generated by default as identity,
    "contentid" bigint NOT NULL,
    "tagid" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    constraint "content_tag_pkey" primary key ("id"),
    constraint "content_tag_contentid_fkey" foreign key ("contentid") references "public"."content" ("id") on delete cascade,
    constraint "content_tag_tagid_fkey" foreign key ("tagid") references "public"."tag" ("id") on delete cascade
  ) tablespace pg_default;

-- 인덱스 생성 (성능 개선)
CREATE INDEX idx_content_userid ON "public"."content" ("userid");
CREATE INDEX idx_tag_userid ON "public"."tag" ("userid");
CREATE INDEX idx_like_userid ON "public"."like" ("userid");
CREATE INDEX idx_like_contentid ON "public"."like" ("contentid");
CREATE INDEX idx_follow_follower ON "public"."follow" ("follower");
CREATE INDEX idx_follow_followee ON "public"."follow" ("followee");
CREATE INDEX idx_content_tag_contentid ON "public"."content_tag" ("contentid");
CREATE INDEX idx_content_tag_tagid ON "public"."content_tag" ("tagid");

-- Row Level Security (선택사항 - 데이터 보호)
ALTER TABLE "public"."user" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."content" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."like" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."follow" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."content_tag" ENABLE ROW LEVEL SECURITY;
